services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true
    environment:
      - APP_KEY=base64:9D5sW8zK9fL3jR6uE2bA1cZ7xY4vG0hN/tP8iO+pKlM=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=":memory:"
      - CACHE_DRIVER=array
      - QUEUE_CONNECTION=sync
      - XDEBUG_MODE=coverage
    depends_on:
      - ftp

  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - USERS=testuser|testpass
      - PASV_ADDRESS=ftp
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
    volumes:
      - ./tests/Fixtures/ftp:/ftp/testuser